"""add stock column to items

Revision ID: 007c8ff1f088
Revises: 57e86c6319b9
Create Date: 2026-06-01 16:57:25.331316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007c8ff1f088'
down_revision: Union[str, Sequence[str], None] = '57e86c6319b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock')
    # ### end Alembic commands ###
